{
    "execution_id": "division_error_20250610_153656_306549",
    "timestamp_utc_start": "2025-06-10T07:36:56.306549+00:00",
    "log_directory_host_path": "D:\\desktop\\autoML\\agent_workspace\\execution_logs\\division_error_20250610_153656_306549",
    "script_filename_by_ai": "division_error.py",
    "script_relative_path_by_ai": "error_tests",
    "ai_code_description": "N/A",
    "ai_code_purpose": "N/A",
    "use_gpu_requested": false,
    "timeout_seconds_set": 3600,
    "cpu_core_limit_set": null,
    "memory_limit_set": null,
    "stdout": "Intentional error incoming...",
    "stderr": "Traceback (most recent call last):\n  File \"/sandbox/code/error_tests/division_error_20250610_153656_306549_division_error.py\", line 2, in <module>\n    x = 1 / 0\n        ~~^~~\nZeroDivisionError: division by zero\n",
    "success": false,
    "exit_code": 1,
    "executed_script_container_path": "/sandbox/code/error_tests/division_error_20250610_153656_306549_division_error.py",
    "code_executed_host_path": "D:\\desktop\\autoML\\agent_workspace\\execution_logs\\division_error_20250610_153656_306549\\error_tests\\division_error_20250610_153656_306549_division_error.py",
    "stdout_log_file_host_path": "D:\\desktop\\autoML\\agent_workspace\\execution_logs\\division_error_20250610_153656_306549\\division_error_20250610_153656_306549.stdout.log",
    "stderr_log_file_host_path": "D:\\desktop\\autoML\\agent_workspace\\execution_logs\\division_error_20250610_153656_306549\\division_error_20250610_153656_306549.stderr.log",
    "metadata_file_host_path": "D:\\desktop\\autoML\\agent_workspace\\execution_logs\\division_error_20250610_153656_306549\\division_error_20250610_153656_306549_ERROR.meta.json",
    "execution_duration_seconds": 0.703,
    "error_message_preprocessing": null,
    "error_message_runtime": null,
    "error_type": "RUNTIME_ERROR",
    "timestamp_utc_end_process": "2025-06-10T07:36:57.083213+00:00",
    "total_tool_duration_seconds": 0.777
}